/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DeckController_getDecks"];
        put?: never;
        post: operations["DeckController_createDeck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deck/{deckId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["DeckController_updateDeck"];
        post?: never;
        delete: operations["DeckController_deleteDeck"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CardController_getCards"];
        put?: never;
        post: operations["CardController_createCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/card/{cardId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["CardController_updateCard"];
        post?: never;
        delete: operations["CardController_deleteCard"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/card/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CardController_getReviewCards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/card/{cardId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CardController_reviewCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** @example john_doe */
            username: string;
            /** @example password123 */
            password: string;
            /** @example john@example.com */
            email?: string;
        };
        AuthResponse: {
            /** @example john_doe */
            username: string;
            /** @example john@example.com */
            email?: string;
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            accessToken: string;
        };
        LoginRequest: {
            /** @example john_doe */
            username: string;
            /** @example password123 */
            password: string;
        };
        RefreshResponse: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            accessToken: string;
        };
        CreateDeckRequest: {
            /** @example My Deck */
            name: string;
            /** @example A deck for studying */
            description?: string;
        };
        DeckResponse: {
            /** @example 1 */
            id: string;
            /** @example My Deck */
            name: string;
            /** @example A deck for studying */
            description?: string;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
        UpdateDeckRequest: {
            /** @example Updated Deck Name */
            name: string;
            /** @example Updated description */
            description?: string;
        };
        /** @enum {number} */
        CardType: 0 | 1;
        CreateCardRequest: {
            /**
             * @description bigint ID of the deck
             * @example 1
             */
            deckId: string;
            /** @example My Card */
            name: string;
            /** @example 0 */
            type: components["schemas"]["CardType"];
            /** @example Card content here */
            content?: string;
            /** @example What is ...? */
            question?: string;
            /** @example The answer is ... */
            answer?: string;
        };
        UpdateCardRequest: {
            /** @example Updated Card Name */
            name: string;
            /** @example Updated content */
            content?: string;
            /** @example Updated question? */
            question?: string;
            /** @example Updated answer */
            answer?: string;
        };
        CardResponse: {
            /** @example 1 */
            id: string;
            /** @example 1 */
            deckId: string;
            /** @example My Card */
            name: string;
            /** @example 0 */
            type: components["schemas"]["CardType"];
            /** @example Card content here */
            content?: string | null;
            /** @example What is ...? */
            question?: string | null;
            /** @example The answer is ... */
            answer?: string | null;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        /**
         * @description 0=AGAIN, 1=HARD, 2=GOOD, 3=EASY
         * @enum {number}
         */
        ReviewRating: 0 | 1 | 2 | 3;
        ReviewCardRequest: {
            /**
             * @description 0=AGAIN, 1=HARD, 2=GOOD, 3=EASY
             * @example 2
             */
            rating: components["schemas"]["ReviewRating"];
            /**
             * @description 楽観ロック用のカードバージョン
             * @example 0
             */
            version: number;
        };
        ReviewPreviewResponse: {
            /**
             * @description AGAINを押した時の次回待ち時間(ms)
             * @example 60000
             */
            again: number;
            /**
             * @description HARDを押した時の次回待ち時間(ms)
             * @example 600000
             */
            hard: number;
            /**
             * @description GOODを押した時の次回待ち時間(ms)
             * @example 3600000
             */
            good: number;
            /**
             * @description EASYを押した時の次回待ち時間(ms)
             * @example 86400000
             */
            easy: number;
        };
        CardReviewResponse: {
            /** @example 1 */
            id: string;
            /** @example 1 */
            deckId: string;
            /** @example My Card */
            name: string;
            /** @example 0 */
            type: components["schemas"]["CardType"];
            /** @example Card content here */
            content?: string | null;
            /** @example What is ...? */
            question?: string | null;
            /** @example The answer is ... */
            answer?: string | null;
            /**
             * @description 0=NEW, 1=SHORT, 2=LONG
             * @example 0
             */
            queue: number;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            nextReviewAt: string;
            /**
             * @description 楽観ロック用バージョン
             * @example 0
             */
            version: number;
            preview?: components["schemas"]["ReviewPreviewResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
    DeckController_getDecks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckResponse"][];
                };
            };
        };
    };
    DeckController_createDeck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeckRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckResponse"];
                };
            };
        };
    };
    DeckController_updateDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description bigint ID of the deck */
                deckId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeckRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckResponse"];
                };
            };
        };
    };
    DeckController_deleteDeck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description bigint ID of the deck */
                deckId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CardController_getCards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CardController_createCard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCardRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CardController_updateCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description bigint ID of the card */
                cardId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCardRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
        };
    };
    CardController_deleteCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description bigint ID of the card */
                cardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CardController_getReviewCards: {
        parameters: {
            query: {
                /** @description bigint ID of the deck */
                deckId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CardController_reviewCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description bigint ID of the card */
                cardId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCardRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardReviewResponse"];
                };
            };
        };
    };
}
